### ISSUE TITLE
Java 17 remove support for curve secp256k1

### ISSUE THREAD

**Issue by FabioPinheiro** [FabioPinheiro/scala-did#236]
DIDComm uses curve secp256k1

https://docs.oracle.com/en/java/javase/17/migrate/removed-tools-and-components.html#GUID-F182E075-858A-4468-9434-8FC1704E7BB7

Test that fail
```scala
fmgp.crypto.JWMSuiteJVM:
==> X fmgp.crypto.JWMSuiteJVM.sign and verify plaintextMessage with Curve SECP256K1  0.202s com.nimbusds.jose.JOSEException: Curve not supported: java.security.spec.ECParameterSpec@7a8b5147
    at com.nimbusds.jose.crypto.ECDSASigner.sign(ECDSASigner.java:287)
    at com.nimbusds.jose.JWSObject.sign(JWSObject.java:299)
    at fmgp.crypto.UtilsJVM$.ecKeySign(UtilsJVM.scala:160)
    at fmgp.crypto.JWMSuiteJVM.$init$$$anonfun$1(JWMSuiteJVM.scala:34)
Caused by: java.security.SignatureException: Curve not supported: java.security.spec.ECParameterSpec@7a8b5147
    at sun.security.ec.ECDSASignature.engineSign(ECDSASignature.java:466)
    at java.security.Signature$Delegate.engineSign(Signature.java:1410)
    at java.security.Signature.sign(Signature.java:713)
    at com.nimbusds.jose.crypto.ECDSASigner.sign(ECDSASigner.java:283)
    ... 3 more
```

**Comment by FabioPinheiro** [comment]
The CI is now testing with java version 17 #245
